services:
  - type: web
    name: pdf-converter
    env: node
    buildCommand: apt-get update && apt-get install -y ghostscript && npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0